### ISSUE TITLE
Create Wireframes for Social Welfare Registration Website

### ISSUE THREAD

**Issue by Maryamsiraj16** [codeforpakistan/NPO-NGO-Registration-System#5]
We created the wireframes and showed them to the government. They requested some changes, so we revised them. Then the government asked us again to make further adjustments, specifically to the color and design. Now, I'm working on implementing both changes.

[https://www.figma.com/proto/pAcgVhZ8IT0g2EcD9nVtZN/social-welfare-department?page-id=0%3A1&node-id=9-2&node-type=frame&viewport=535%2C325%2C0.09&t=6rNV5hRrYt40MDpW-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=9%3A2](url)

**Comment by muhammadhakim821** [comment]
Assisting on the Wireframe Design
